// <auto-generated />
using Entrepot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Entrepot.Migrations
{
    [DbContext(typeof(EntrepotContext))]
    [Migration("20180304073213_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entrepot.Models.Fiche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Designation");

                    b.HasKey("Id");

                    b.ToTable("Fiches");
                });

            modelBuilder.Entity("Entrepot.Models.LigneProduit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Designation");

                    b.Property<Guid?>("FicheId");

                    b.Property<Guid>("Fiche_Id");

                    b.Property<Guid?>("ProduitId");

                    b.Property<Guid>("Produit_Id");

                    b.Property<int>("Quantite");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LigneProduits");
                });

            modelBuilder.Entity("Entrepot.Models.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Designation");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Entrepot.Models.LigneProduit", b =>
                {
                    b.HasOne("Entrepot.Models.Fiche", "Fiche")
                        .WithMany("LignesProduit1")
                        .HasForeignKey("FicheId");

                    b.HasOne("Entrepot.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");
                });
#pragma warning restore 612, 618
        }
    }
}
